Repository woohaengshi/frontend, pull requests merged in 2024-08, with the labels that each got.

#6 5 feature record calendar
  app/layout.tsx
  app/page.tsx
  app/record/page.tsx
  app/reset.css
  components/common/Header.module.css
  components/common/Header.tsx
  components/common/HeaderNav.tsx
  components/record/FullCalendar.jsx
  components/record/FullCalendar.module.css
  package-lock.json
  package.json
Labels: ✨ feature

#9 [refactor/#5]:달력 컴포넌트 분리 및 코드 리팩토링
  .eslintrc.json
  components/record/FullCalendar.jsx
  components/record/FullCalendar.module.css
  components/record/FullCalendar.tsx
  components/record/MonthPicker.module.css
  components/record/MonthPicker.tsx
  package-lock.json
Labels: ♻️ refactor

#18 [feat/#2]: 헤더 주메뉴 중앙 정렬
  components/common/Header.module.css
  components/common/Header.tsx
  components/common/HeaderNav.tsx
Labels: ✨ feature

#19 [refactor/#17]:마이페이지 탭메뉴 객체배열로 변환
  app/mypage/layout.module.css
  app/mypage/layout.tsx
  app/mypage/page.tsx
  app/mypage/pwupdate/page.tsx
  app/mypage/subjectedit/page.tsx
  app/reset.css
  components/common/ButtonSubmit.module.css
  components/common/ButtonSubmit.tsx
  components/mypage/MypageTabMenu.tsx
  components/mypage/UserProfile.module.css
Labels: ♻️ refactor

#21 1 feature timer code merge
  app/study/page.tsx
  components/study/Timer.module.css
  components/study/Timer.tsx
Labels: 🐞bug, ✨ feature

#29 [style/#28]: Pretendard font 적용
  app/font.css
  app/reset.css
  public/fonts/Pretendard-Black.subset.woff
  public/fonts/Pretendard-Bold.subset.woff
  public/fonts/Pretendard-Medium.subset.woff
  public/fonts/Pretendard-Regular.subset.woff
  public/fonts/Pretendard-Thin.subset.woff
Labels: ✨ feature

#34 [feat/#31]:헤더 반응형 구현
  app/layout.module.css
  app/layout.tsx
  components/common/Header/Header.module.css
  components/common/Header/Header.tsx
  components/common/Header/HeaderNav.tsx
  components/common/Header/MobileHeader.module.css
  components/common/Header/MobileHeader.tsx
Labels: ✨ feature

#36 [style/#17]: 마이페이지 스타일 수정
  app/mypage/layout.module.css
  app/mypage/layout.tsx
  app/reset.css
  components/mypage/MypageTabMenu.module.css
  components/mypage/MypageTabMenu.tsx
Labels: ✨ feature

#35 [feat/#32]:버튼 컴포넌트 분리
  app/mypage/pwupdate/page.tsx
  components/common/ButtonSubmit.module.css
  components/common/ButtonSubmit.tsx
  components/common/CommonButton.module.css
  components/common/CommonButton.tsx
Labels: ✨ feature

#42 [rename]: 마이페이지 이미지 경로 수정
  app/mypage/page.tsx
  public/imgs/medal_first_on.svg
Labels: 🐞bug

#43 [feat/#17]:마이페이지 과목편집 컴포넌트 적용
  app/mypage/subjectedit/page.tsx
Labels: ✨ feature

#40 [fix/#32]:Link 스타일 수정
  components/common/CommonButton.module.css
Labels: 🐞bug

#46 [style/#31]:모바일 메뉴 스타일 수정
  components/common/Header/MobileHeader.module.css
  components/common/Header/MobileHeader.tsx
Labels: 🐞bug, ✨ feature

#45 44 feature timer css
  .eslintrc.json
  app/study/page.module.css
  components/study/Timer.module.css
  components/study/Timer.tsx
  components/study/TimerToggleBtn.tsx
  package.json
Labels: ✨ feature, ♻️ refactor

#41 [feat/#39]:auth 스타일링 통일
  app/(auth)/join/page.jsx
  app/(auth)/join/page.tsx
  app/(auth)/layout.module.css
  app/(auth)/layout.tsx
  app/(auth)/login/page.jsx
  app/(auth)/login/page.module.css
  app/(auth)/login/page.tsx
  app/(auth)/pwfind/page.jsx
  app/(auth)/pwfind/page.tsx
Labels: 🐞bug, ✨ feature

#47 [style/#17]: 마이페이지 탭메뉴 z-index 수정
  components/mypage/MypageTabMenu.module.css
Labels: 🐞bug

#51 [style/#50]:버튼 컴포넌트 스타일링 수정
  app/(auth)/join/page.tsx
  app/(auth)/login/page.tsx
  app/mypage/pwupdate/page.tsx
  app/reset.css
  components/common/CommonButton.module.css
  components/common/CommonButton.tsx
  package-lock.json
Labels: ✨ feature, ♻️ refactor

#54 53 feature api settings
  .gitignore
  api/instance.ts
  api/study.ts
  app/study/page.module.css
  app/study/page.tsx
  components/study/SubjectEditForm.module.css
  components/study/SubjectSelect.tsx
  components/study/SubjectSelectButton.tsx
  components/study/Timer.tsx
  middleware.ts
  package-lock.json
  package.json
Labels: ✨ feature, ♻️ refactor

#62 [feat/#59] 로그인/회원가입/타이머 API 연동
  api/auth.ts
  api/instance.ts
  api/study.ts
  app/(auth)/join/page.tsx
  app/(auth)/layout.module.css
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/study/page.tsx
  components/auth/AuthForm.module.css
  components/auth/AuthFormLayout.tsx
  components/auth/InputField.tsx
  components/auth/JoinForm.tsx
  components/auth/LoginForm.tsx
  components/common/CommonButton.module.css
  components/common/CommonButton.tsx
  components/study/SubjectEdit.tsx
  components/study/SubjectEditForm.tsx
  components/study/SubjectSelect.tsx
  components/study/SubjectSelectButton.tsx
  components/study/Timer.tsx
  components/study/TimerToggleBtn.tsx
  store/authStore.ts
  store/studyStore.ts
  types/study.ts
Labels: 🐞bug, ✨ feature, ♻️ refactor

#60 [feat/#56]: 기록확인 API 셋팅 (갱신)
  api/recordApi.ts
  app/record/page.tsx
  components/record/CalendarRecord.module.css
  components/record/CalendarRecord.tsx
  components/record/FullCalendar.module.css
  components/record/FullCalendar.tsx
  components/record/MonthPicker.tsx
  package-lock.json
  package.json
  store/recordStore.ts
Labels: ✨ feature, ♻️ refactor

#66 [style/#64]: 랭킹 레이아웃 수정
  app/ranking/page.tsx
  app/ranking/ranking.module.css
  components/ranking/fullRankingList.module.css
  components/ranking/fullRankingList.tsx
Labels: ✨ feature, ♻️ refactor

#71 [style/#70]: eslint 적용
  app/(auth)/login/page.tsx
  app/(auth)/pwfind/page.tsx
  app/layout.tsx
  app/mypage/layout.tsx
  components/common/Header/Header.tsx
  components/mypage/MypageTabMenu.module.css
  components/mypage/MypageTabMenu.tsx
  components/mypage/UserProfile.module.css
  components/mypage/UserProfile.tsx
  components/ranking/topLanking.tsx
  components/record/FullCalendar.tsx
  components/record/MonthPicker.tsx
  components/study/Timer.tsx
Labels: 🚨 hotfix, ♻️ refactor

#65 [feat/#56]: 연간 달력 API 연동
  api/rankingApi.ts
  api/recordApi.ts
  app/record/page.tsx
  components/record/CalendarRecord.module.css
  components/record/CalendarRecord.tsx
  components/record/FullCalendar.module.css
  components/record/FullCalendar.tsx
  components/record/MonthPicker.module.css
  components/record/MonthPicker.tsx
  utils/levelUtils.ts
Labels: ✨ feature, ♻️ refactor

#74 [fix/#73]: tsc CI 해결
  components/mypage/UserProfile.tsx
  components/study/SubjectForm.tsx
  components/study/SubjectSelectButton.tsx
  components/study/Timer.tsx
  global.d.ts
  package-lock.json
  package.json
  store/studyStore.ts
  types/studyType.ts
Labels: 🐞bug, 🚨 hotfix

#67 [fix/#58]:과목 선택 api 연결 초기 셋팅
  .github/ISSUE_TEMPLATE/feature_issue_template.md
  .github/pull_request_template.md
  .prettierrc
  README.md
  api/instance.ts
  api/subjectEditApi.ts
  api/subjectFormApi.ts
  app/font.css
  app/layout.module.css
  app/mypage/layout.module.css
  app/mypage/page.module.css
  app/mypage/subjectedit/page.tsx
  app/ranking/ranking.module.css
  app/reset.css
  components/common/Header/Header.module.css
  components/common/Header/MobileHeader.module.css
  components/ranking/fullRankingList.module.css
  components/ranking/fullRankingList.tsx
  components/ranking/topLanking.tsx
  components/ranking/topRankingList.module.css
  components/record/CalendarRecord.module.css
  components/record/FullCalendar.module.css
  components/study/SubjectEditForm.tsx
  components/study/SubjectForm.module.css
  components/study/SubjectForm.tsx
  components/study/SubjectSelectForm.tsx
  components/study/Timer.module.css
  middleware.ts
  package-lock.json
  store/subjectStore.ts
Labels: ✨ feature

#69 [feat/#59]: 액세스토큰 재발급
  api/authApi.ts
  api/instance.ts
  app/(auth)/login/page.tsx
  middleware.ts
Labels: ✨ feature

#80 [feat/#75]: 모달 컴포넌트 생성
  app/layout.tsx
  app/record/page.tsx
  app/reset.css
  components/common/Modal/LanchBody.tsx
  components/common/Modal/Modal.module.css
  components/common/Modal/Modal.tsx
  components/common/Modal/ModalLink.module.css
  components/common/Modal/ModalLink.tsx
  package-lock.json
  package.json
  public/fonts/timeout.png
  public/fonts/timerout.png
  public/imgs/ico_link.svg
Labels: ✨ feature

#82 [feat/#81]: 마이페이지 비밀번호 수정 API 연결
  api/memberApi.ts
  app/mypage/pwupdate/page.tsx
  components/mypage/PwUpdateForm.tsx
  store/memberStore.ts
Labels: ✨ feature

#78 [feat/#76]: 스타일 점검
  api/userApi.ts
  app/mypage/layout.tsx
  app/mypage/page.tsx
  components/auth/LoginForm.tsx
  components/common/Header/Header.tsx
  components/common/Header/HeaderNav.tsx
  components/common/Header/MobileHeader.tsx
  components/common/SmallButton.module.css
  components/common/SmallButton.tsx
  components/mypage/UserProfile.tsx
  components/record/FullCalendar.module.css
Labels: ✨ feature

#84 [rename]: userApi -> memberApi로 통합
  api/memberApi.ts
  api/userApi.ts
Labels: ♻️ refactor

#87 [feat/#64]: 탑랭킹 레이아웃 수정
  app/ranking/page.module.css
  app/ranking/page.tsx
  components/ranking/topLanking.tsx
  components/ranking/topRanking.tsx
  components/ranking/topRankingList.module.css
Labels: ♻️ refactor

#90 [feat/#88]: 유저정보 API 연결
  app/mypage/layout.tsx
  components/auth/LoginForm.tsx
  components/common/Header/Header.tsx
  components/mypage/UserProfile.tsx
  components/record/FullCalendar.tsx
  hook/useRefreshMonthlyData.ts
  hook/useUserInfo.ts
  store/memberStore.ts
Labels: ✨ feature

#91 [fix/#56]: 월간 달력 오류 수정
  components/record/FullCalendar.tsx
  components/record/MonthPicker.tsx
  store/recordStore.ts
Labels: 🐞bug

#102 [feat]: 루트 페이지 이스터에그 추가
  app/mypage/layout.tsx
  app/mypage/page.tsx
  app/page.tsx
  public/easteregg/0.jpg
  public/easteregg/1.jpg
  public/easteregg/2.jpg
  public/easteregg/bg.jpg
Labels: ✨ feature
